### ISSUE TITLE
Please add a warning on the frontpage that data is send to ChatGPT

### ISSUE THREAD

**Issue by jjtbsomhorst** [badlogic/skystats-v2#2]
Hi, 

on the frontpage the statement '  No data is collected, not even your IP address.' is a false one. Since the records that where created the last 30 days are send to ChatGPT something is recorded. Also please be so kind to add a warning to the frontpage that data IS send to ChatGPT.

**Comment by badlogic** [comment]
Good catch! I added the LLM summaries later and forgot about the footer. Updated the footer with concrete information what happens with the data that is sent to OpenAI.
